# -*- coding: utf-8 -*-
"""Streamlit adding two numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/193aYlrrdDaGDMJAYiJqlNeUSofr13Krc
"""

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

st.title('Number')

number = st.number_input('Insert a number')
if number%2==0:
  st.write('The number is even')
else:
  st.write('The number is odd')